//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProcesoImsa.gt.com.imsa.handheldws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsServicioFarmaciaImsaSoap", Namespace="http://wsServicioFarmaciaImsa")]
    public partial class wsServicioFarmaciaImsa : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setConsumoMedicamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsServicioFarmaciaImsa() {
            this.Url = global::ProcesoImsa.Properties.Settings.Default.ProcesoImsa_gt_com_imsa_handheldws_wsServicioFarmaciaImsa;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setConsumoMedicamentoCompletedEventHandler setConsumoMedicamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wsServicioFarmaciaImsa/setConsumoMedicamento", RequestNamespace="http://wsServicioFarmaciaImsa", ResponseNamespace="http://wsServicioFarmaciaImsa", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsFarmaciaImsaResponse setConsumoMedicamento(clsFarmaciaImsaRequest clsFarmaciaImsaReq) {
            object[] results = this.Invoke("setConsumoMedicamento", new object[] {
                        clsFarmaciaImsaReq});
            return ((clsFarmaciaImsaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setConsumoMedicamentoAsync(clsFarmaciaImsaRequest clsFarmaciaImsaReq) {
            this.setConsumoMedicamentoAsync(clsFarmaciaImsaReq, null);
        }
        
        /// <remarks/>
        public void setConsumoMedicamentoAsync(clsFarmaciaImsaRequest clsFarmaciaImsaReq, object userState) {
            if ((this.setConsumoMedicamentoOperationCompleted == null)) {
                this.setConsumoMedicamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetConsumoMedicamentoOperationCompleted);
            }
            this.InvokeAsync("setConsumoMedicamento", new object[] {
                        clsFarmaciaImsaReq}, this.setConsumoMedicamentoOperationCompleted, userState);
        }
        
        private void OnsetConsumoMedicamentoOperationCompleted(object arg) {
            if ((this.setConsumoMedicamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setConsumoMedicamentoCompleted(this, new setConsumoMedicamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsServicioFarmaciaImsa")]
    public partial class clsFarmaciaImsaRequest {
        
        private clsEncabezado[] clsEncabezadoField;
        
        private clsDetalle[] clsDetalleField;
        
        /// <remarks/>
        public clsEncabezado[] ClsEncabezado {
            get {
                return this.clsEncabezadoField;
            }
            set {
                this.clsEncabezadoField = value;
            }
        }
        
        /// <remarks/>
        public clsDetalle[] ClsDetalle {
            get {
                return this.clsDetalleField;
            }
            set {
                this.clsDetalleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsServicioFarmaciaImsa")]
    public partial class clsEncabezado {
        
        private string cod_empleadoField;
        
        private string codigo_transaccionField;
        
        private string fechaField;
        
        private string totalField;
        
        private string pagosyeField;
        
        /// <remarks/>
        public string cod_empleado {
            get {
                return this.cod_empleadoField;
            }
            set {
                this.cod_empleadoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_transaccion {
            get {
                return this.codigo_transaccionField;
            }
            set {
                this.codigo_transaccionField = value;
            }
        }
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string pagosye {
            get {
                return this.pagosyeField;
            }
            set {
                this.pagosyeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsServicioFarmaciaImsa")]
    public partial class clsFarmaciaImsaResponse {
        
        private string cod_errorField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string cod_error {
            get {
                return this.cod_errorField;
            }
            set {
                this.cod_errorField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsServicioFarmaciaImsa")]
    public partial class clsDetalle {
        
        private string correlativoField;
        
        private string cod_empleadoField;
        
        private string codigo_transaccionField;
        
        private string cantidadField;
        
        private string montoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string correlativo {
            get {
                return this.correlativoField;
            }
            set {
                this.correlativoField = value;
            }
        }
        
        /// <remarks/>
        public string cod_empleado {
            get {
                return this.cod_empleadoField;
            }
            set {
                this.cod_empleadoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_transaccion {
            get {
                return this.codigo_transaccionField;
            }
            set {
                this.codigo_transaccionField = value;
            }
        }
        
        /// <remarks/>
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public string monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void setConsumoMedicamentoCompletedEventHandler(object sender, setConsumoMedicamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setConsumoMedicamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setConsumoMedicamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsFarmaciaImsaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsFarmaciaImsaResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591